stages:
  - test

default:
  cache:
    key: ${CI_COMMIT_REF_SLUG}

test-frontend:
  image: node:12-alpine
  cache:
    paths:
      - $CI_PROJECT_DIR/hyakumori_crm/static/hyakumori_crm/node_modules/
  before_script:
    - cd hyakumori_crm/static/hyakumori_crm
    - yarn install
  script:
    - yarn lint
    - yarn test --passWithNoTests

test-backend:
  image: python:3.7
  services:
    - postgres:11-alpine

  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    POSTGRES_DB: hyakumori
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: "youC4nP4ass"
    POSTGRES_HOST_AUTH_METHOD: trust
  cache:
    paths:
      - .cache/pip
  script:
    - export HYAKUMORI_LIGHT_BUILD=1
    - export DATABASE_URL=postgres://runner:youC4nP4ass@postgres:5432/hyakumori
    - pip install -U pip setuptools
    - pip install '.[dev]'
    - coverage run -m pytest tests
    - coverage report -m
