stages:
  - test

default:
  cache:
    key: ${CI_COMMIT_REF_SLUG}

test-frontend:
  image: node:12-alpine
  cache:
    paths:
      - $CI_PROJECT_DIR/hyakumori_crm/static/hyakumori_crm/node_modules/
  before_script:
    - cd hyakumori_crm/static/hyakumori_crm
    - yarn install
  script:
    - yarn lint
    - yarn test --passWithNoTests

test-backend:
  image: python:3.7
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip
  script:
    - export HYAKUMORI_LIGHT_BUILD=1
    - pip install -U pip setuptools
    - pip install '.[dev]'
    - ./manage.py test
